Pin flask-caching to 1.7.2 for now
Due to ImportError: cannot import name 'iteritems' from 'flask_caching'
(/usr/local/lib/python3.8/site-packages/flask_caching/__init__.py)